services:
  mysql:
    image: mysql:latest
    container_name: mysql_GeoFinder
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: geoFinder
       MYSQL_USER: root
       MYSQL_PASSWORD: root
    ports:
      - "3306:3306"


  springboot-container:
    build:
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_NAME: geoFinder
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_GeoFinder:3306/geoFinder
    ports:
      - "8080:8080"
    links:
      - mysql